// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybqkrmnS-SGf1p-qk4hzfomEPQ6FpVDI',
    appId: '1:630453572446:web:8b6d2842ca9169bf81b5cf',
    messagingSenderId: '630453572446',
    projectId: 'dummyfire-4cd85',
    authDomain: 'dummyfire-4cd85.firebaseapp.com',
    storageBucket: 'dummyfire-4cd85.appspot.com',
    measurementId: 'G-WDK4P1DC1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASkif7Sy2_TaIchzVn5H5KSlMVymFquME',
    appId: '1:630453572446:android:bd33df96cbb428fc81b5cf',
    messagingSenderId: '630453572446',
    projectId: 'dummyfire-4cd85',
    storageBucket: 'dummyfire-4cd85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIItJu2l9jkRDSfvFE545bdVZfWJ3Nr18',
    appId: '1:630453572446:ios:04a72f76f9e6326781b5cf',
    messagingSenderId: '630453572446',
    projectId: 'dummyfire-4cd85',
    storageBucket: 'dummyfire-4cd85.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIItJu2l9jkRDSfvFE545bdVZfWJ3Nr18',
    appId: '1:630453572446:ios:3fa2e581cc7b2ff881b5cf',
    messagingSenderId: '630453572446',
    projectId: 'dummyfire-4cd85',
    storageBucket: 'dummyfire-4cd85.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
